### ISSUE TITLE
[BUG] [UI] "select custom timeframe" breaks UI on Firefox

### ISSUE THREAD

**Issue by nil0x42** [netdata/netdata-cloud#219]
**Describe the bug**	
On firefox, in netdata cloud (app.netdata.cloud), the entire UI turns into blank screen when clicking custom timeframe selection button:

click here:
![Screenshot_2021-12-11_15-15-19](https://user-images.githubusercontent.com/3504393/145682731-7ab08ef3-2dfc-459a-bcaf-ce0676b5f45b.png)

after clicking (with devtools open):
![Screenshot_2021-12-11_15-51-54](https://user-images.githubusercontent.com/3504393/145682869-ca4a8b55-d1aa-4c44-b930-a68f5ad3774e.png)

The blank page URL is this one:
https://app.netdata.cloud/spaces/my-space/rooms/general/dashboards/my-dashboard#correlation=false&after=1639234872000&before=1639235773000&utc=undefined&offset=&metrics_correlation=false

**To Reproduce**	
Click `custom timeframe`

**Expected behavior**	
Open timeframe selection pane

**Error logs**	
When clicked, two `RangeError: Invalid time value` errors are raised on developper tools.

**Desktop (please complete the following information):**	
 - OS: ubuntu 20.04
 - Browser: firefox 78.15.0esr (64-bit)

**Additional context**	
On chrome, it works as expected.

**Comment by jjtsou** [comment]
The issue is described [here](https://stackoverflow.com/questions/37798404/getting-timezone-using-intl-api-doesnt-work-in-firefox)

**Comment by dionysis-netdata** [comment]
fix released

**Comment by jjtsou** [comment]
@nil0x42 Is the bug fixed on your side?
We will be pleased to have your input on this, because we made a fix but this was a user specific bug.

**Comment by nil0x42** [comment]
Hi @jjtsou, the issue is not fixed on my side...
It's curious i've been the only one to report that bug.

I tried again with a fresh firefox from a virtual machine to make sure it's not related to my firefox plugins. And even on my VM, the issue is still here.

**Comment by jjtsou** [comment]
@nil0x42 Thanks a lot for your input.
Reopening the ticket.

**Comment by jjtsou** [comment]
@nil0x42 Hello again, I hope you are doing great.
We just made a release with a potential fix about your issue.
Is the bug fixed on your side?
