### ISSUE TITLE
[Bug]: No data in chart displayed although data are there

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#440]
### Bug description

Charts canvases show a no data message, but data are there. 

### Expected behavior

The no data message shouldn't be displayed.

### Steps to reproduce

1. Login to netdata cloud
2. Claim a node
3. Navigate to overview tab
4. Check chart canvas

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/170984132-44fbe938-1771-4ed0-be82-0876e1325d7e.png)

### Error Logs

No error logs

### Desktop

OS: MacOs
Browser: Chrome
Browser Version: 101

**Comment by hugovalente-pm** [comment]
@jjtsou another bug on FE that I just pushed to our board

**Comment by dimko** [comment]
This isn't yet fixed.

![image](https://user-images.githubusercontent.com/19268853/173049115-5a50d7d1-dba9-4bf4-95b0-3988693e36f8.png)

**Comment by dimko** [comment]
This has been fixed. Closing
