### ISSUE TITLE
[Bug]: anomaly rate pop down chart seems unaligned

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#662]
### Bug description

seems like the anomaly rate pop down chart is a bit misaligned for some reason.

![image](https://user-images.githubusercontent.com/2178292/202503479-7ff36bf6-228f-4f42-afb3-6e4652025228.png)

### Expected behavior

should line up

### Steps to reproduce

1. open anomaly rate chart

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@andrewm4894 was checking this today and this seems to be fixed, can you confirm from your side?
![image](https://user-images.githubusercontent.com/82235632/202667744-737aca5b-7687-437e-a526-8a8d10122935.png)

**Comment by andrewm4894** [comment]
@hugovalente-pm @novykh it looks to be fixed apart from one last thing being that the new chart level filters dont seem to be reflected in the anomaly rate pop down chart: 

![image](https://user-images.githubusercontent.com/2178292/202694138-3f89c2cb-f077-4e74-a5ca-b05830120882.png)

I can make a new issue for this if we want?

**Comment by hugovalente-pm** [comment]
> @hugovalente-pm @novykh it looks to be fixed apart from one last thing being that the new chart level filters dont seem to be reflected in the anomaly rate pop down chart:

great catch @andrewm4894 , yes lets open a separate bug for that

**Comment by andrewm4894** [comment]
this is still unfixed

**Comment by hugovalente-pm** [comment]
@jacekkolasa is looking into this and seems to be caused by the animation when expanding and collapsing the anomaly bit chart
this animation doesn't exist on the Anomalies tab so we could probably remove it if we don't find an easy way around it

https://user-images.githubusercontent.com/82235632/208947862-f2009e57-4ad5-4e85-83b2-ee868aaa067f.mp4

**Comment by jacekkolasa** [comment]
As @hugovalente-pm shown, the easiest way of reproducing the bug was to open anomaly bit twice.
I deployed a fix to PROD which just disables the animation

**Comment by hugovalente-pm** [comment]
thanks for fixing this @jacekkolasa , yes we can look into the animation at a later stage

**Comment by andrewm4894** [comment]
@jacekkolasa @hugovalente-pm i am still seeing this - see video here. not sure exactly how to reproduce or anything but have this example we can drill into easy enough

https://user-images.githubusercontent.com/2178292/214264530-3313bb77-5a14-4f0e-b027-6723863fd817.mp4

**Comment by andrewm4894** [comment]
actually disregard - loosk like a different new bug raised here on agent: https://github.com/netdata/netdata/issues/14318
