### ISSUE TITLE
[Bug]: child/parent/cloud and basic auth issue on local dashboard

### ISSUE THREAD

**Issue by pzwahlen** [netdata/netdata-cloud#891]
### Bug description

I have an issue with basic auth that started with 1.41. I have also tested this on a brand new deployement.

I have a couple headless childs (docker) streaming to a parent (docker). Port 19999 on the parent is opened for everyone in the LAN. The parent's dashboard is behind an haproxy (docker, tls/443) with basic auth. I have restricted access to the dashboards to be only possible via the haproxy with (haproxy.haproxy_back is the FQDN for the haproxy docker on the 'bachend' network):

```
[web]
    allow dashboard from = haproxy.haproxy_back
    allow badges from = haproxy.haproxy_back
    allow netdata.conf from = haproxy.haproxy_back
    allow management from = haproxy.haproxy_back
    allow streaming from = *
```

That works well, until I claim the parent in netdata-cloud.

After the claiming, the cloud dashboard shows me all the hosts (childs and parent). However, the local parent's dashboard doesn't work anymore, with a basic auth popup getting in the way (and no way to authenticate with success).

As soon as I remove the requirement for basic auth, the local dashboard works fine (temporary workaround).

The first request that generates the auth popup is:

`Jul 23 09:45:35 docker74.lan.local haproxy[1184]: 192.168.X.Y:52641 [23/Jul/2023:09:45:35.972] f_https_in~ b_http_netdata/<NOSRV> 0/-1/-1/-1/0 401 252 - - LR-- 1/1/0/0/0 0/0 {netdata.lan.local|https://netdata.lan.local/spaces/netdatalanlocal/rooms/local/overview|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36||en-US,en;q=0.9,fr;q=0.8} "GET https://netdata.lan.local//api/v2/data?points=334&format=json2&time_group=average&time_resampling=0&after=1690097436&before=1690098336&group_by%5B0%5D=instance&group_by_label%5B0%5D=&aggregation%5B0%5D=sum&group_by%5B1%5D=selected&group_by_label%5B1%5D=&aggregation%5B1%5D=avg&options=jsonwrap%7Cnonzero%7Cflip%7Cms%7Cjw-anomaly-rates%7Cminify&contexts=*&scope_contexts=system.cpu&scope_nodes=*&nodes=*&instances=*&dimensions=*&labels=* HTTP/2.0" 0/0000000000000000/0/0/0 netdata.lan.local/TLSv1.3/TLS_AES_256_GCM_SHA384`

That seems to be a valid request and if I simply copy/paste it in a browser's address bar, I get the auth popup and then valid json output.

Happy to help figure out what might cause this issue.

### Expected behavior

Local parent's dhasboard behind an authenticating proxy should continue to work after connection to cloud.

### Steps to reproduce

As described in the issue.

**Comment by hugovalente-pm** [comment]
thanks for raising this @pzwahlen , we will take a look and ask for more information if needed

**Comment by novykh** [comment]
@pzwahlen in the latest nightly this should be fixed, could you upgrade and check? 

The issue was happening because of conflict between basic and bearer tokens. This happen when you claim an agent to the cloud, then we provide a way for you to "lock" your agent and be available only for signed in cloud members that have access to that specific agent in the cloud space (hope it makes sense the way I wrote it, cc @ktsaou to provide more info if needed).
So the issue was that we were providing a bearer token in the Authorization header, making the browser to ditch the basic Auth header.

Feel free to re-open this issue if you upgrade and still have issues.

**Comment by pzwahlen** [comment]
I just upgraded my dockerized on-prem parent to v1.42.0-57-nightly (as reported by Netdata Cloud) and I still cannot reach it if I enable basic auth.

Did this change make it to the docker version, too ?

**Comment by hugovalente-pm** [comment]
@pzwahlen picking up this, yes once a release on the agent repo it (should) be made available on all sources
from what you shared this is still happening so the issues should re reopened
